nfq_assistance_request_form:
    path:     /requestForm
    defaults: { _controller: NFQAssistanceBundle:Assistance:requestForm }

nfq_assistance_request_list:
    path:     /request-list
    defaults: { _controller: NFQAssistanceBundle:Assistance:requestList }

nfq_assistance_match_tags:
    path:     /mt
    defaults: { _controller: NFQAssistanceBundle:Assistance:matchTags }

nfq_assistance_save_tags:
    path:     /st
    defaults: { _controller: NFQAssistanceBundle:Assistance:saveTags }

nfq_assistance_remove_tags:
    path:     /rmt
    defaults: { _controller: NFQAssistanceBundle:Assistance:removeTags }

nfq_assistance_selected_tags:
    path:     /mytags
    defaults: { _controller: NFQAssistanceBundle:Assistance:myTags }

nfq_assistance_not_done:
    path:     /notDone/{arid}
    defaults: { _controller: NFQAssistanceBundle:Assistance:notDone }
nfq_assistance_suggest_tag:
    path:     /suggest-tag
    defaults: { _controller: NFQAssistanceBundle:Assistance:suggestTag }

nfq_assistance_cancel:
    path:     /cancel/{arid}
    defaults: { _controller: NFQAssistanceBundle:Assistance:cancel }

nfq_assistance_helper_cancel:
    path:     /helperCancel/{arid}
    defaults: { _controller: NFQAssistanceBundle:Assistance:helperCancel }

nfq_assistance_help:
    path:     /help/{arid}
    defaults: { _controller: NFQAssistanceBundle:Assistance:help }