nfq_assistance_request_form:
    path:     /requestForm
    defaults: { _controller: NFQAssistanceBundle:Assistance:requestForm }

nfq_assistance_request_submitted:
    path:     /sucessfullySubmitted
    defaults: { _controller: NFQAssistanceBundle:Assistance:requestSubmitted }

nfq_assistance_request_list:
    path:     /request-list
    defaults: { _controller: NFQAssistanceBundle:Assistance:requestList }

nfq_assistance_request_category:
    path:     /request-category
    defaults: { _controller: NFQAssistanceBundle:Assistance:requestCategory }
