services:
    nfq_assistance.assistance_manager:
        class: NFQ\AssistanceBundle\Service\AssistanceManager
        arguments: ["@doctrine.orm.default_entity_manager"]

    nfq_assitance.twig.assistance_extension:
        class: NFQ\AssistanceBundle\Twig\AssitanceExtension
        arguments: ["@nfq_assistance.assistance_manager"]
        tags:
            - { name: twig.extension }

    nfq_assitance.entity_listener.tag_populate:
        class: NFQ\AssistanceBundle\EventListener\Doctrine\TagListener
        arguments: ["@es.manager.default.tag"]
        tags:
            - { name: doctrine.orm.entity_listener, entity: Nfq\AssistanceBundle\Entity\Tags, event: prePersist }
            - { name: doctrine.orm.entity_listener, entity: Nfq\AssistanceBundle\Entity\Tags, event: postUpdate }
            - { name: doctrine.orm.entity_listener, entity: Nfq\AssistanceBundle\Entity\Tags, event: preRemove }
            - { name: doctrine.orm.entity_listener, entity: Nfq\AssistanceBundle\Entity\Tags, event: postRemove }