services:
    nfq_assistance.assistance_manager:
        class: NFQ\AssistanceBundle\Service\AssistanceManager
        arguments: ["@doctrine.orm.default_entity_manager"]

    nfq_assitance.twig.assistance_extension:
        class: NFQ\AssistanceBundle\Twig\AssitanceExtension
        arguments: ["@nfq_assistance.assistance_manager"]
        tags:
            - { name: twig.extension }
