nfq_assistance:
    resource: "@NFQAssistanceBundle/Resources/config/routing.yml"
    prefix:   /assistance

nfq_home:
    resource:   "@NFQHomeBundle/Resources/config/routing.yml"
    prefix:     /

nfq_frontend:
    resource: "@NFQFrontendBundle/Resources/config/routing.yml"
    prefix:   /front

nfq_apie:
    resource: "@NFQApieBundle/Resources/config/routing.yml"
    prefix:   /apie