nfq_home:
    resource: "@NFQHomeBundle/Resources/config/routing.yml"
    prefix:   /
    
nfq_frontend:
    resource: "@NFQFrontendBundle/Resources/config/routing.yml"
    prefix:   /

nfq_apie_homepage:
    path:     /apie
    defaults: { _controller: NFQApieBundle:Apie:apie }
