# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    nfq.form.registration:
        class: NFQ\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: nfq_user_registration }
    nfq.form.profile:
            class: NFQ\UserBundle\Form\ProfileType
            tags:
                - { name: form.type, alias: nfq_user_profile }