home:
    path:     /
    defaults: { _controller: NFQHomeBundle:Home:home }

signup:
    path:     /signup
    defaults: { _controller: NFQHomeBundle:Home:signup }

profile:
    path:     /profile
    defaults: { _controller: NFQHomeBundle:Home:profile }
