<?php

namespace NFQ\AssistanceBundle\Entity;

/**
 * AssistanceEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssistanceEventRepository extends \Doctrine\ORM\EntityRepository
{
}
